# Generated by Django 5.1.5 on 2025-01-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='Subject', max_length=255),
            preserve_default=False,
        ),
    ]
